APP-654 FE samples docs
symphonyoss/App-Integrations-FE-Commons pull request #36
Opened 2017-05-30 17:25 UTC by ecarrenho-daitan

Adjustments on Sample documents.

2017-05-30 19:50 UTC, luanapp requested changes

2017-05-30 19:50 UTC, aurojr commented on samples/out-of-the-box-configurator/README.md
> +The samples folder is set up with multiple development samples built up with [webpack][webpack] and [eslint][eslint]. Every time you change a file and save it, eslint checks your code sintaxe and web
I think webpack does not reload the browser itself, it only recompiles the bundle file in the served folder

2017-05-31 16:28 UTC, ecarrenho-daitan commented on samples/out-of-the-box-configurator/README.md
> +The samples folder is set up with multiple development samples built up with [webpack][webpack] and [eslint][eslint]. Every time you change a file and save it, eslint checks your code sintaxe and web
Done.

2017-05-31 16:34 UTC, luanapp requested changes

2017-05-31 16:34 UTC, aurojr commented on samples/posting-location-sample/README.md
> +<<<<<<< Updated upstream
I think this shouldn't be here! ;-)

2017-05-31 16:39 UTC, luanapp approved these changes

2017-05-31 16:40 UTC, merged